import RecentMatches from "../../components/player/recent/recentMatches";
import Head from "next/head";
import Profile from "../../components/player/profile";
import { Box } from "@mui/system";
import { Typography } from "@mui/material";
import Heroes from "../../components/player/heroes";

function Player({ player, heroes, mode, lobby, counts, wl }) {
  return (
    <>
      <Head>
        <title>{player.profile.personaname} overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Box sx={{display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)' }}>
			<Box>
				<Heroes id={player.profile.account_id} heroData={heroes}/>
			</Box>
				<Box>
        	<Profile player={player} counts={counts} wl={wl} />	
				</Box>
				<Box>
				<Typography variant="h6" component="div">
				Recent Matches
				</Typography>
					<RecentMatches
						id={player.profile.account_id}
						heroes={heroes}
						mode={mode}
						lobby={lobby}
					/>
				</Box>
			</Box>
    </>
  );
}

export async function getServerSideProps(context) {
  const playerId = context.params.player;
  const playerData = await fetch(
    `https://api.opendota.com/api/players/${playerId}`
  );
  const player = await playerData.json();
  const heroesData = await fetch(
    `https://api.opendota.com/api/constants/heroes`
  );
  const heroes = await heroesData.json();
  const modeData = await fetch(
    `https://api.opendota.com/api/constants/game_mode`
  );
  const mode = await modeData.json();
  const lobbyData = await fetch(
    `https://api.opendota.com/api/constants/lobby_type`
  );
  const lobby = await lobbyData.json();
  const countsData = await fetch(
    `https://api.opendota.com/api/players/${playerId}/counts`
  );
  const counts = await countsData.json();
  const wlData = await fetch(
    `https://api.opendota.com/api/players/${playerId}/wl`
  );
  const wl = await wlData.json();

  return {
    props: {
      player,
      heroes,
      mode,
      lobby,
      counts,
      wl,
    },
  };
}

export default Player;
