import RecentMatches from "../../components/player/recent/recentMatches";
import Head from "next/head";
import styles from "../../styles/Player.module.scss";
import Profile from "../../components/player/profile";
import Item from "../../components/summary/item";
import { useEffect, useState } from "react";
import Summary from "../../components/summary";
import Main from "../../components/layout/main";
import Aside from "../../components/aside";
import { Box } from "@mui/system";
function Player({ playerId, player, heroes, mode, lobby, counts, wl }) {
  const [matches, setMatches] = useState([]);
  const [kills, setKills] = useState(0);
  const [assists, setAssists] = useState(0);
  const [deaths, setDeaths] = useState(0);
  const [wins, setWins] = useState(0);
  const [losses, setLosses] = useState(0);
  const [winrate, setWinrate] = useState(0);
  useEffect(() => {
    getRecentMatches(playerId);
  }, []);

  function getRecentMatches(id) {
    fetch(`https://api.opendota.com/api/players/${id}/recentMatches`)
      .then((res) => res.json())
      .then((data) => {
        setMatches(data);
        getSummary();
      });
  }

  function getSummary() {
    let totalKills = 0;
    let totalDeaths = 0;
    let totalAssists = 0;
    let won = 0;
    let lost = 0;
    matches.forEach((match) => {
      totalKills += match.kills;
      totalDeaths += match.deaths;
      totalAssists += match.assists;

      match.player_slot <= 127 && match.radiant_win ? (won += 1) : (lost += 1);
    });
    let winrate = ((won / (won + lost)) * 100).toFixed(2);
    setKills(totalKills);
    setDeaths(totalDeaths);
    setAssists(totalAssists);
    setWins(won);
    setLosses(lost);
    setWinrate(winrate);
  }

  return (
    <>
      <Head>
        <title>{player.profile.personaname} overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Box sx={{display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)' }}>
        <RecentMatches
          recent={matches}
          heroes={heroes}
          mode={mode}
          lobby={lobby}
        />
        {/* <Summary style={styles.summary} items={styles.items}>
          <Item style={styles.item} desc={`Winrate: ${winrate}%`} />
          <Item style={styles.item} desc={`Won: ${wins}`} />
          <Item style={styles.item} desc={`Lost: ${losses}`} />
          <Item style={styles.item} desc={`Kills: ${kills}`} />
          <Item style={styles.item} desc={`Deaths: ${deaths}`} />
        </Summary> */}
        <Profile player={player} counts={counts} wl={wl} />
			</Box>
    </>
  );
}

export async function getServerSideProps(context) {
  const playerId = context.params.player;
  const playerData = await fetch(
    `https://api.opendota.com/api/players/${playerId}`
  );
  const player = await playerData.json();
  const heroesData = await fetch(
    `https://api.opendota.com/api/constants/heroes`
  );
  const heroes = await heroesData.json();
  const modeData = await fetch(
    `https://api.opendota.com/api/constants/game_mode`
  );
  const mode = await modeData.json();
  const lobbyData = await fetch(
    `https://api.opendota.com/api/constants/lobby_type`
  );
  const lobby = await lobbyData.json();
  const countsData = await fetch(
    `https://api.opendota.com/api/players/${playerId}/counts`
  );
  const counts = await countsData.json();
  const wlData = await fetch(
    `https://api.opendota.com/api/players/${playerId}/wl`
  );
  const wl = await wlData.json();

  return {
    props: {
      playerId,
      player,
      heroes,
      mode,
      lobby,
      counts,
      wl,
    },
  };
}

export default Player;
