import Head from 'next/head'
import Link from 'next/link'
import Navbar from '../components/nav'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Reactive Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Navbar />
      
					<Link href="/players/170365079">
						My Personal Profile
					</Link>
    </div>
  )
}
